apiVersion: v1
kind: Service
metadata:
  name: simple-api-app-svc
spec:
  selector:
    app: simple-api-app
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-api-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-api-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
# status:
#   observedGeneration: 1
#   lastScaleTime: <some-time>
#   currentReplicas: 1
#   desiredReplicas: 1
#   currentMetrics:
#   - type: Resource
#     resource:
#       name: cpu
#       current:
#         averageUtilization: 0
#         averageValue: 0


# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: simple-api-app
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: simple-api-app
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 50