apiVersion: v1
kind: Service
metadata:
  name: simple-api-app-svc
  namespace: default
spec:
  selector:
    app: simple-api-app-dpl
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
