apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-api-app
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-api-app
  minReplicas: 1
  maxReplicas: 5

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
      selectPolicy: Min
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50

  # behavior:
  #   scaleDown:
  #     stabilizationWindowSeconds: 30
  #     policies:
  #     - type: Pods
  #       value: 1
  #       periodSeconds: 30
  #     - type: Percent
  #       value: 100
  #       periodSeconds: 30
  #     selectPolicy: Min
  #   scaleUp:
  #     stabilizationWindowSeconds: 0
  #     policies:
  #     - type: Percent
  #       value: 50
  #       periodSeconds: 10
  #     - type: Pods
  #       value: 4
  #       periodSeconds: 15
  #     selectPolicy: Max
  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 50
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: AverageValue
  #       averageValue: 200Mi