apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: simple-api-app
  template:
    metadata:
      labels:
        app: simple-api-app
    spec:
      containers:
        - name: simple-api-app
          image: oseasjs/simple-api-app:1.3
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "50Mi"
              cpu: "250m"
            limits:
              memory: "300Mi"
              cpu: "700m"