apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-api-app
  template:
    metadata:
      labels:
        app: simple-api-app
    spec:
      containers:
        - name: simple-api-app
          image: simple-api-app:latest
          ports:
            - containerPort: 3000