apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api-app
  template:
    metadata:
      labels:
        app: simple-api-app
    spec:
      containers:
        - name: simple-api-app
          image: oseasjs/simple-api-app:1.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "50Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "2000m"