apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-app-dpl
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: simple-api-app
  template:
    metadata:
      labels:
        app: simple-api-app
      # annotations:
      #   config.linkerd.io/proxy-cpu-limit: "1"
      #   config.linkerd.io/proxy-cpu-request: "0.1"
      #   config.linkerd.io/proxy-memory-limit: 500m
      #   config.linkerd.io/proxy-memory-request: 128Mi
    spec:
      containers:
        - name: simple-api-app
          imagePullPolicy: Always
          image: oseasjs/simple-api-app:1.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
          # resources:
          #   requests:
          #     memory: 128Mi
          #     cpu: 200m
          #   limits:
          #     memory: 256Mi
          #     cpu: 500m